spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead
    username: matheus
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
  liquibase:
    change-log: classpath:db.changelog/db.changelog-root.yaml
    enabled: false
